// Copyright 2008 Google Inc. All Rights Reserved.

package com.google.caja.parser.quasiliteral;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Describes each transformation rule
 * 
 * @author jasvir@google.com (Jasvir Nagra)
 *
 */
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface RuleDescription {
  /**
   * @return Name of the transformation {@code Rule}
   */
  String name();
  
  /**
   * @return Summary of the effect of {@code Rule}
   */
  String synopsis();
  
  /**
   * @return Reason that necessitates {@code Rule}
   */  
  String reason();

  /**
   * @return Quasiliteral pattern matched by {@code Rule}
   */  
  String matches() default "UNKNOWN";

  /**
   * @return Code generated by {@code Rule}
   */  
  String substitutes() default "UNKNOWN";
}
